"""Configuration parameters for this example."""

DATABASE_FILE = "./database_sym.sqlite"
NUM_REPETITIONS = 1
NUM_SIMULATORS = 4
POPULATION_SIZE = 10
OFFSPRING_SIZE = 10
NUM_GENERATIONS = 10
TOURNAMENT_SIZE = 5
SIM_TIME = 30
