"""Configuration parameters for this example."""

DATABASE_FILE = "./database_sym.sqlite"
NUM_REPETITIONS = 3
NUM_SIMULATORS = 8
POPULATION_SIZE = 100
OFFSPRING_SIZE = 100
NUM_GENERATIONS = 100
TOURNAMENT_SIZE = 6
SIM_TIME = 30
