"""Configuration parameters for this example."""

DATABASE_FILE = "./big_exp001.sqlite"
NUM_REPETITIONS = 1
NUM_SIMULATORS = 8
POPULATION_SIZE = 10
OFFSPRING_SIZE = 10
NUM_GENERATIONS = 3
TOURNAMENT_SIZE = 5
SIM_TIME = 30
